#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  8 12:06:35 2021

@author: blink
"""
import numpy as np
import random
n=10000
population=list(range(n))
status=np.zeros(n)


#Randomly select one person who gets the message
lastSelected=random.choice(population)
status[lastSelected]=1
spread=1
layer=1
while(spread<=len(population)):
    lastSelected=random.sample(population,spread)
    for i in lastSelected:
        status[i]=1
    spread*=2
    print(sum(status),' people got the message in ',layer,' layer')
    layer+=1


lastSelected=random.sample(population,n)
for i in lastSelected:
    status[i]=1
spread*=2
print(sum(status),' people got the message in ',layer,' layer')